export interface HealthScoreInputs {
  runwayMonths: number | null;
  revenueChangePct: number;
  expenseChangePct: number;
  grossMarginPct: number; // (revenue - direct costs) / revenue
  receivablesAgingSharePct: number;
  payablesOverduePct: number;
  topCustomerSharePct: number;
  topSupplierSharePct: number;
  cashFlowVolatility: number; // coefficient of variation of monthly net cash flow, 0..1+
}

export interface HealthScoreFactor {
  label: string;
  points: number; // signed
}

export interface HealthScoreResult {
  score: number; // 0-100
  band: "CRITICAL" | "AT_RISK" | "STABLE" | "HEALTHY" | "STRONG";
  positives: HealthScoreFactor[];
  negatives: HealthScoreFactor[];
}

function bandFor(score: number): HealthScoreResult["band"] {
  if (score >= 85) return "STRONG";
  if (score >= 65) return "HEALTHY";
  if (score >= 45) return "STABLE";
  if (score >= 25) return "AT_RISK";
  return "CRITICAL";
}

/**
 * Deterministic weighted scorecard, starting from a 50-point baseline.
 * Every point swing is attributable to one named factor below — nothing is
 * generated by an LLM. Weights are documented in docs/architecture.md.
 */
export function computeHealthScore(inputs: HealthScoreInputs): HealthScoreResult {
  const positives: HealthScoreFactor[] = [];
  const negatives: HealthScoreFactor[] = [];
  let score = 50;

  const add = (label: string, points: number) => {
    score += points;
    if (points >= 0) positives.push({ label, points });
    else negatives.push({ label, points });
  };

  if (inputs.runwayMonths === null) add("No net cash burn detected", 10);
  else if (inputs.runwayMonths >= 6) add("Strong cash runway (6+ months)", 12);
  else if (inputs.runwayMonths >= 4) add("Healthy cash buffer", 6);
  else if (inputs.runwayMonths >= 2) add("Cash runway under 4 months", -8);
  else add("Cash runway under 2 months", -20);

  if (inputs.revenueChangePct >= 0.03) add("Revenue growing", 8);
  else if (inputs.revenueChangePct >= -0.03) add("Revenue stable", 4);
  else if (inputs.revenueChangePct >= -0.1) add("Revenue softening", -6);
  else add("Revenue declining sharply", -14);

  if (inputs.expenseChangePct <= 0.03) add("Expenses under control", 6);
  else if (inputs.expenseChangePct <= 0.1) add("Expenses rising moderately", -4);
  else add("Expenses rising sharply", -12);

  if (inputs.grossMarginPct >= 0.4) add("Healthy gross margin", 8);
  else if (inputs.grossMarginPct >= 0.2) add("Moderate gross margin", 2);
  else add("Thin gross margin", -8);

  if (inputs.receivablesAgingSharePct <= 0.1) add("Low receivables leakage", 6);
  else if (inputs.receivablesAgingSharePct <= 0.25) add("Receivables aging is elevated", -6);
  else add("Receivables aging is high", -14);

  if (inputs.payablesOverduePct <= 0.05) add("Supplier payments on time", 4);
  else if (inputs.payablesOverduePct > 0.2) add("Overdue supplier payments accumulating", -8);

  if (inputs.topCustomerSharePct <= 0.15) add("Low customer concentration", 6);
  else if (inputs.topCustomerSharePct > 0.35) add("High customer concentration", -10);

  if (inputs.topSupplierSharePct <= 0.2) add("Low supplier concentration", 4);
  else if (inputs.topSupplierSharePct > 0.45) add("High supplier dependency", -8);

  if (inputs.cashFlowVolatility <= 0.3) add("Stable month-to-month cash flow", 6);
  else if (inputs.cashFlowVolatility > 0.7) add("Highly volatile cash flow", -10);

  score = Math.max(0, Math.min(100, Math.round(score)));

  return { score, band: bandFor(score), positives, negatives };
}
